# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170209_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='pictures'),
        ),
    ]
