# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feels', to='core.Recipe'),
        ),
        migrations.AlterField(
            model_name='feel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feels', to=settings.AUTH_USER_MODEL),
        ),
    ]
